FROM python:3.11-slim as builder

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_VERSION=2.0.1 \
    POETRY_HOME="/opt/poetry" \
    POETRY_NO_INTERACTION=1 \
    PATH="/opt/poetry/bin:$PATH"

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get -y upgrade && \
    apt-get install --no-install-recommends -y \
        curl \
        build-essential \
        ffmpeg \
        espeak

RUN python -m pip install --upgrade pip setuptools && \
    python -m pip install "poetry==2.0.1" && \
    poetry --version
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app
COPY poetry.lock pyproject.toml ./
RUN poetry lock --no-update || true
RUN which poetry || true && \
    poetry --version || true && \
    poetry debug info || true && \
    poetry install --only main --no-root

COPY . /app
RUN poetry install --only main