[tool.pylint.master]
load-plugins = [
    "pylint.extensions.bad_builtin",
    "pylint.extensions.mccabe",
    "pylint.extensions.check_elif",
    "pylint.extensions.eq_without_hash",
    "pylint.extensions.private_import",
    "pylint.extensions.redefined_variable_type",
    "pylint.extensions.overlapping_exceptions",
    "pylint.extensions.empty_comment",
    "pylint.extensions.set_membership",
    "pylint.extensions.typing",
    "pylint.extensions.while_used",
]
extension-pkg-whitelist = ["pydantic"]
ignore = ["migrations/*"]

[tool.pylint.basic]
good-names = ["i", "j", "k", "ex", "Run", "_", "to", "q", "f", "db", "id"]

[tool.pylint.messages_control]
disable = [
    "consider-using-from-import",
    "while-used",
    "wrong-import-order",
    "too-few-public-methods",
    "too-many-arguments",
    "deprecated-typing-alias",
    "duplicate-code",
]

[tool.pylint.format]
max-line-length = 88

[tool.pylint.similarities]
ignore-signatures = true
ignore-imports = true

[tool.pylint.imports]
ignore-signatures = true
ignore-imports = true
