steps:
  # Build the Docker image and inject secrets
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "NEXT_PUBLIC_FIREBASE_API_KEY environment variable: $$NEXT_PUBLIC_FIREBASE_API_KEY"
        echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN environment variable: $$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
        echo "NEXT_PUBLIC_FIREBASE_APP_ID environment variable: $$NEXT_PUBLIC_FIREBASE_APP_ID"
        echo "NEXT_PUBLIC_API_URL environment variable: $$NEXT_PUBLIC_API_URL"
        echo "NEXT_PUBLIC_TUTORIAL_BUCKET environment variable: $PROJECT_ID-store-public-files"
        docker build -t us-east1-docker.pkg.dev/$PROJECT_ID/app-stt/frontend:$SHORT_SHA \
          --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY \
          --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
          --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=$$NEXT_PUBLIC_FIREBASE_APP_ID \
          --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID \
          --build-arg NEXT_PUBLIC_API_URL=$$NEXT_PUBLIC_API_URL \
          --build-arg NEXT_PUBLIC_LOOKER=liabi.cloud.looker.com \
          --build-arg NEXT_PUBLIC_LOOKER_GENERAL_DASHBOARD_ID=1 \
          --build-arg NEXT_PUBLIC_LOOKER_LEARNERS_DASHBOARD_ID=2 \
          --build-arg NEXT_PUBLIC_TUTORIAL_BUCKET=$PROJECT_ID-store-public-files \
          .
    secretEnv: ['NEXT_PUBLIC_FIREBASE_API_KEY', 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN', 'NEXT_PUBLIC_FIREBASE_APP_ID','NEXT_PUBLIC_API_URL']
    
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/${PROJECT_ID}/app-stt/frontend:$SHORT_SHA",
      ]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "frontend-v2",
        "--project=${PROJECT_ID}",
        "--image",
        "us-east1-docker.pkg.dev/${PROJECT_ID}/app-stt/frontend:$SHORT_SHA",
        "--region",
        "us-east1",
        "--service-account",
        "sa-${PROJECT_NUMBER}-front-engine@${PROJECT_ID}.iam.gserviceaccount.com",
        "--update-secrets=NEXT_PUBLIC_FIREBASE_API_KEY=apiKey:latest,NEXT_PUBLIC_FIREBASE_APP_ID=appId:latest,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=authDomain:latest,API_URL=api_url:latest",
        "--set-env-vars=NEXT_PUBLIC_FIREBASE_PROJECT_ID=${PROJECT_ID},NEXT_PUBLIC_LOOKER=liabi.cloud.looker.com,NEXT_PUBLIC_LOOKER_GENERAL_DASHBOARD_ID=1,NEXT_PUBLIC_LOOKER_LEARNERS_DASHBOARD_ID=2,NEXT_PUBLIC_TUTORIAL_BUCKET=rad-stt-dev-store-public-files",
        "--allow-unauthenticated",
        "--vpc-connector=vpc-con",
      ]

images:
  - "us-east1-docker.pkg.dev/${PROJECT_ID}/app-stt/frontend:$SHORT_SHA"

availableSecrets:
      secretManager:
        - versionName: projects/${PROJECT_ID}/secrets/apiKey/versions/latest
          env: 'NEXT_PUBLIC_FIREBASE_API_KEY'
        - versionName: projects/${PROJECT_ID}/secrets/authDomain/versions/latest
          env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
        - versionName: projects/${PROJECT_ID}/secrets/appId/versions/latest
          env: 'NEXT_PUBLIC_FIREBASE_APP_ID'
        - versionName: projects/{$PROJECT_ID}/secrets/api_url/versions/latest
          env: 'NEXT_PUBLIC_API_URL'

options:
  logging: CLOUD_LOGGING_ONLY
