"""remove unused column from exam_user

Revision ID: 25e2e05c5fc5
Revises: 859443e79a80
Create Date: 2023-05-19 13:03:16.885723+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e2e05c5fc5'
down_revision = '859443e79a80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams_users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams_users', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
