"""Add last_login to user

Revision ID: 23190f5d61ae
Revises: c25b24a75bec
Create Date: 2023-05-13 12:17:04.495349+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "23190f5d61ae"
down_revision = "c25b24a75bec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_login", sa.DateTime(timezone=True)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login")
    # ### end Alembic commands ###
