"""Add county column

Revision ID: bdae7a246545
Revises: 767598457f03
Create Date: 2023-10-14 17:22:06.199104+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdae7a246545'
down_revision = '767598457f03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('county', sa.String(length=50), nullable=True))
    op.execute(
        """
        UPDATE organizations
            SET county = 'N/A'
        WHERE county IS NULL;
        """
    )
    op.alter_column('organizations', 'county', nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'county')
    # ### end Alembic commands ###
