"""Fix foreign key relationship

Revision ID: 4a191094de13
Revises: 179d5b1a2c55
Create Date: 2023-05-20 19:51:35.428574+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a191094de13'
down_revision = '179d5b1a2c55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exams_users_questions_organization_id_fkey', 'exams_users_questions', type_='foreignkey')
    op.create_foreign_key(None, 'exams_users_questions', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams_users_questions', type_='foreignkey')
    op.create_foreign_key('exams_users_questions_organization_id_fkey', 'exams_users_questions', 'groups', ['organization_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
