"""Add generation to session

Revision ID: 2814eb6402f3
Revises: 172b63b65b0c
Create Date: 2023-05-01 19:06:36.845939+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2814eb6402f3'
down_revision = '172b63b65b0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('generation', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'generation')
    # ### end Alembic commands ###
