"""Dropping foreign key constraint for EUQ

Revision ID: 2fa71d14d1f1
Revises: e9164fbde28d
Create Date: 2023-06-18 13:43:47.282684+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa71d14d1f1'
down_revision = 'e9164fbde28d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exams_users_questions_group_id_fkey', 'exams_users_questions', type_='foreignkey')
    op.drop_constraint('exams_users_questions_user_id_fkey', 'exams_users_questions', type_='foreignkey')
    op.drop_constraint('exams_users_questions_exam_id_fkey', 'exams_users_questions', type_='foreignkey')
    op.drop_constraint('exams_users_questions_organization_id_fkey', 'exams_users_questions', type_='foreignkey')
    op.drop_constraint('exams_users_questions_question_id_fkey', 'exams_users_questions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('exams_users_questions_question_id_fkey', 'exams_users_questions', 'questions', ['question_id'], ['id'])
    op.create_foreign_key('exams_users_questions_organization_id_fkey', 'exams_users_questions', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('exams_users_questions_exam_id_fkey', 'exams_users_questions', 'exams', ['exam_id'], ['id'])
    op.create_foreign_key('exams_users_questions_user_id_fkey', 'exams_users_questions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('exams_users_questions_group_id_fkey', 'exams_users_questions', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
