"""Add session model

Revision ID: 172b63b65b0c
Revises: 686a54dca68e
Create Date: 2023-05-01 15:00:34.180918+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "172b63b65b0c"
down_revision = "686a54dca68e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "users", "firebase_id", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "users", "email_address", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.create_unique_constraint(None, "users", ["firebase_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "email_address", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "users", "firebase_id", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.drop_table("sesssions")
    # ### end Alembic commands ###
