"""Multiple choice questions

Revision ID: f110ee740ac4
Revises: c0aacf06c865
Create Date: 2024-12-01 20:47:21.633130+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision = 'f110ee740ac4'
down_revision = 'c0aacf06c865'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answers', JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'answers')
    # ### end Alembic commands ###