"""adicionando novos user_ratings

Revision ID: ad5881f8f440
Revises: 6e58dc35f77d
Create Date: 2024-06-07 20:18:03.050606+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5881f8f440'
down_revision = '6e58dc35f77d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrating ADD VALUE 'PRE_READER_TWO'")
    op.execute("ALTER TYPE userrating ADD VALUE 'PRE_READER_THREE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE exams_users SET user_rating = 'NO_RATING' WHERE user_rating IN ('PRE_READER_TWO', 'PRE_READER_THREE')")

    op.execute("CREATE TYPE userrating_tmp AS ENUM('NO_RATING', 'FLUENT', 'READER', 'PRE_READER_ONE', 'PRE_READER_FOUR')")
    op.execute("""
        ALTER TABLE exams_users 
        ALTER COLUMN user_rating TYPE userrating_tmp 
        USING user_rating::text::userrating_tmp
    """)
    op.execute("DROP TYPE userrating")
    op.execute("ALTER TYPE userrating_tmp RENAME TO userrating")
    # ### end Alembic commands ###
