"""adding formatted_data to question

Revision ID: 60da2f57f9af
Revises: 6349ef8435cb
Create Date: 2024-03-03 16:16:53.934649+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60da2f57f9af'
down_revision = '6349ef8435cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('formatted_data', sa.Text(), nullable=True))
    op.execute("UPDATE questions SET formatted_data = data")
    op.alter_column('questions', 'formatted_data', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'formatted_data')
    # ### end Alembic commands ###
