"""adding new question type

Revision ID: ce130db65df2
Revises: 60da2f57f9af
Create Date: 2024-03-25 21:42:38.283909+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce130db65df2'
down_revision = '60da2f57f9af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE questiontype ADD VALUE 'COMPLEX_WORDS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE questions SET type = 'WORDS' WHERE type = 'COMPLEX_WORDS'")

    op.execute("CREATE TYPE questiontype_tmp AS ENUM('WORDS', 'PHRASES')")
    op.execute("""
        ALTER TABLE questions 
        ALTER COLUMN type TYPE questiontype_tmp 
        USING type::text::questiontype_tmp
    """)
    op.execute("DROP TYPE questiontype")
    op.execute("ALTER TYPE questiontype_tmp RENAME TO questiontype")
    # ### end Alembic commands ###
