"""Add user and total accuracy to question data

Revision ID: 6e58dc35f77d
Revises: 5068b03bf199
Create Date: 2024-04-16 23:43:45.456348+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e58dc35f77d'
down_revision = '5068b03bf199'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams_users_questions', sa.Column('user_accuracy', sa.FLOAT(), nullable=True))
    op.add_column('exams_users_questions', sa.Column('total_accuracy', sa.FLOAT(), nullable=True))
    op.execute(
        """
        UPDATE exams_users_questions as euq
            set user_accuracy=CASE 
                                WHEN jsonb_array_length(euq.result) != 0 THEN euq.right_count::float/jsonb_array_length(euq.result)::float
                                ELSE 0
                              END,
                total_accuracy=euq.right_count::float/array_length(string_to_array(regexp_replace(regexp_replace(q.data, '[\[\]\.,\(\)!-\?]', '', 'g'), '\s+', ' ', 'g'), ' '), 1)::float
            from questions q
            where euq.question_id = q.id;
        """
    )
    op.alter_column('exams_users_questions', 'user_accuracy', nullable=False)
    op.alter_column('exams_users_questions', 'total_accuracy', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams_users_questions', 'total_accuracy')
    op.drop_column('exams_users_questions', 'user_accuracy')
    # ### end Alembic commands ###
