"""adding shifts enum

Revision ID: c0aacf06c865
Revises: ad5881f8f440
Create Date: 2024-06-27 19:07:33.839701+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0aacf06c865'
down_revision = 'ad5881f8f440'
branch_labels = None
depends_on = None
shifts_enum = postgresql.ENUM('MORNING', 'AFTERNOON', 'EVENING', 'ALLDAY', name='shifts')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    shifts_enum.create(op.get_bind())
    op.alter_column('groups', 'shift',
               existing_type=sa.VARCHAR(length=50),
               type_=shifts_enum,
               existing_nullable=False,
               postgresql_using="shift::shifts")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'shift',
               existing_type=shifts_enum,
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using="shift::text")
    shifts_enum.drop(op.get_bind())
    # ### end Alembic commands ###
