"""criando temas para questões

Revision ID: a6308cf92433
Revises: a70edd0ba9c2
Create Date: 2025-03-28 21:37:13.326023+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6308cf92433'
down_revision = 'a70edd0ba9c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    question_theme = postgresql.ENUM(
        'MONICA_AGUA_BOA',
        'O_MENINO_MALUQUINHO',
        'O_PEQUENO_PRINCIPE',
        name="questiontheme",
        create_type=False,
    )
    question_theme.create(op.get_bind(), checkfirst=False)
    op.add_column('questions', sa.Column('theme', postgresql.ENUM('MONICA_AGUA_BOA', 'O_MENINO_MALUQUINHO', 'O_PEQUENO_PRINCIPE', name='questiontheme'), nullable=True))
    op.execute("ALTER TYPE questiontype ADD VALUE 'INDUSTRY_AREAS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'theme')
    op.execute("DROP TYPE questiontheme")
    op.execute("UPDATE questions SET type = 'WORDS' WHERE type = 'INDUSTRY_AREAS'")

    op.execute("CREATE TYPE questiontype_tmp AS ENUM('WORDS', 'COMPLEX_WORDS', 'PHRASES', 'MULTIPLE_CHOICE', 'UNDERSTANDING_CHECK', 'LOGICAL_SITUATIONS', 'SHORT_EXPLANATIONS')")

    op.execute("""
        ALTER TABLE questions 
        ALTER COLUMN type TYPE questiontype_tmp 
        USING type::text::questiontype_tmp
    """)

    op.execute("DROP TYPE questiontype")

    op.execute("ALTER TYPE questiontype_tmp RENAME TO questiontype")
    # ### end Alembic commands ###
