"""adicionando ai exam feedback

Revision ID: 11f0ba4cc131
Revises: 158293312726
Create Date: 2025-03-07 19:52:22.806507+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f0ba4cc131'
down_revision = '158293312726'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams_users', sa.Column('ai_exam_feedback', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams_users', 'ai_exam_feedback')
    # ### end Alembic commands ###
