"""adicionando ai output em exam users questions

Revision ID: 158293312726
Revises: 9f1670fbfa55
Create Date: 2025-02-25 20:15:26.127430+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158293312726'
down_revision = '9f1670fbfa55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams_users_questions', sa.Column('ai_feedback', sa.String(length=1000), nullable=True))
    op.add_column('exams_users_questions', sa.Column('ai_is_correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams_users_questions', 'ai_is_correct')
    op.drop_column('exams_users_questions', 'ai_feedback')
    # ### end Alembic commands ###
