"""change field value

Revision ID: fc6f3fff50ca
Revises: a6308cf92433
Create Date: 2025-12-11 22:48:02.748123+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'fc6f3fff50ca'
down_revision = 'a6308cf92433'
branch_labels = None
depends_on = None
    
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE questiontype RENAME TO questiontype_old")
    op.execute("ALTER TYPE questiontheme RENAME TO questiontheme_old")

    op.execute("""
        CREATE TYPE questiontype AS ENUM(
            'WORDS', 
            'COMPLEX_WORDS', 
            'PHRASES', 
            'MULTIPLE_CHOICE', 
            'UNDERSTANDING_CHECK', 
            'LOGICAL_SITUATIONS', 
            'SHORT_EXPLANATIONS', 
            'SPECIFIC_KNOWLEDGE'
        )
    """)
    op.execute("""
        CREATE TYPE questiontheme AS ENUM(
            'MONICA_AGUA_BOA',
            'O_MENINO_MALUQUINHO',
            'O_PEQUENO_PRINCIPE'
        )
    """)

    op.execute("""
        ALTER TABLE questions 
        ALTER COLUMN type TYPE questiontype 
        USING (
            CASE 
                WHEN type::text = 'INDUSTRY_AREAS' THEN 'SPECIFIC_KNOWLEDGE'
                ELSE type::text 
            END
        )::questiontype,
        ALTER COLUMN theme TYPE questiontheme 
        USING (NULL::questiontheme)
    """)

    op.execute("DROP TYPE questiontype_old")
    op.execute("DROP TYPE questiontheme_old")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE questiontype RENAME TO questiontype_old")
    op.execute("ALTER TYPE questiontheme RENAME TO questiontheme_old")

    op.execute("""
        CREATE TYPE questiontype AS ENUM(
            'WORDS', 
            'COMPLEX_WORDS', 
            'PHRASES', 
            'MULTIPLE_CHOICE', 
            'UNDERSTANDING_CHECK', 
            'LOGICAL_SITUATIONS', 
            'SHORT_EXPLANATIONS', 
            'INDUSTRY_AREAS'
        )
    """)
    op.execute("""
        CREATE TYPE questiontheme AS ENUM(
            'FOOD_AND_BEVERAGES',
            'ELECTRONICS',
            'NON_METALLIC_MATERIALS',
            'TELECOMMUNICATIONS',
            'SOFTWARE_IT'
        )
    """)

    op.execute("""
        ALTER TABLE questions 
        ALTER COLUMN type TYPE questiontype 
        USING (
            CASE 
                WHEN type::text = 'SPECIFIC_KNOWLEDGE' THEN 'INDUSTRY_AREAS'
                ELSE type::text 
            END
        )::questiontype,
        ALTER COLUMN theme TYPE questiontheme 
        USING (NULL::questiontheme)
    """)

    op.execute("DROP TYPE questiontype_old")
    op.execute("DROP TYPE questiontheme_old")
    # ### end Alembic commands ###