"""removendo valores nao usados

Revision ID: a70edd0ba9c2
Revises: 11f0ba4cc131
Create Date: 2025-03-26 21:34:18.419357+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70edd0ba9c2'
down_revision = '11f0ba4cc131'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM roles WHERE name = 'user'")).fetchone()
    student_role_id = result[0] if result else None

    if student_role_id:
        op.execute(
            f"""
            UPDATE users SET role_id = '{student_role_id}' WHERE role_id IN (SELECT id FROM roles WHERE name IN ('school_manager', 'county_manager', 'ed_regional_manager', 'state_manager'));
            """
        )

    op.execute(
        """
        DELETE 
            FROM roles 
            WHERE name in 
                ('school_manager', 'county_manager', 'ed_regional_manager', 'state_manager');
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO roles (id, name, display_name, description, scopes, created_at, updated_at)
        VALUES (
            uuid_generate_v4(), 'school_manager', '{"pt-BR": "Gestor de Escola", "en-US": "School Manager", "es-ES": "Director de Escuela"}', '{"pt-BR": "Gestor de Escola", "en-US": "School Manager", "es-ES": "Director de Escuela"}', '["dashboard.viewer"]', NOW(), NOW()
        )
        """
    )
    op.execute(
        """
        INSERT INTO roles (id, name, display_name, description, scopes, created_at, updated_at)
        VALUES (
            uuid_generate_v4(), 'county_manager', '{"pt-BR": "Gestor de Município", "en-US": "County Manager", "es-ES": "Gerente municipal"}', '{"pt-BR": "Gestor de Município", "en-US": "County Manager", "es-ES": "Gerente municipal"}', '["dashboard.viewer"]', NOW(), NOW()
        )
        """
    )
    op.execute(
        """
        INSERT INTO roles (id, name, display_name, description, scopes, created_at, updated_at)
        VALUES (
            uuid_generate_v4(), 'ed_regional_manager', '{"pt-BR": "Gestor da Regional de Educação", "en-US": "Regional Education Manager", "es-ES": "Gerente Regional de Educacíon"}', '{"pt-BR": "Gestor da Regional de Educação", "en-US": "Regional Education Manager", "es-ES": "Gerente Regional de Educacíon"}', '["dashboard.viewer"]', NOW(), NOW()
        )
        """
    )
    op.execute(
        """
        INSERT INTO roles (id, name, display_name, description, scopes, created_at, updated_at)
        VALUES (
            uuid_generate_v4(), 'state_manager', '{"pt-BR": "Gestor Estadual", "en-US": "State Manager", "es-ES": "Gerente Estatal"}', '{"pt-BR": "Gestor Estadual", "en-US": "State Manager", "es-ES": "Gerente Estatal"}', '["dashboard.viewer"]', NOW(), NOW()
        )
        """
    )
    # ### end Alembic commands ###
