"""adding new question types

Revision ID: 9f1670fbfa55
Revises: 446cda185324
Create Date: 2025-02-22 03:07:46.365282+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1670fbfa55'
down_revision = '446cda185324'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE questiontype ADD VALUE 'UNDERSTANDING_CHECK'")
    op.execute("ALTER TYPE questiontype ADD VALUE 'LOGICAL_SITUATIONS'")
    op.execute("ALTER TYPE questiontype ADD VALUE 'SHORT_EXPLANATIONS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE questions SET type = 'WORDS' WHERE type = 'UNDERSTANDING_CHECK'")
    op.execute("UPDATE questions SET type = 'WORDS' WHERE type = 'LOGICAL_SITUATIONS'")
    op.execute("UPDATE questions SET type = 'WORDS' WHERE type = 'SHORT_EXPLANATIONS'")

    op.execute("CREATE TYPE questiontype_tmp AS ENUM('WORDS', 'COMPLEX_WORDS', 'PHRASES', 'MULTIPLE_CHOICE')")

    op.execute("""
        ALTER TABLE questions 
        ALTER COLUMN type TYPE questiontype_tmp 
        USING type::text::questiontype_tmp
    """)

    op.execute("DROP TYPE questiontype")

    op.execute("ALTER TYPE questiontype_tmp RENAME TO questiontype")
    # ### end Alembic commands ###