"""Add indexes properly

Revision ID: 446cda185324
Revises: f5757084df5d
Create Date: 2025-01-22 17:51:33.203027+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446cda185324'
down_revision = 'f5757084df5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_exam_grade', 'exams', ['grade'], unique=False)
    op.create_index('ix_exam_start_end_date', 'exams', ['start_date', 'end_date'], unique=False)
    op.create_index('ix_exam_user_exam_user_id', 'exams_users', ['exam_id', 'user_id'], unique=False)
    op.create_index('ix_exam_user_question_group_organization_id', 'exams_users_questions', ['group_id', 'organization_id'], unique=False)
    op.create_index('ix_exam_user_question_question_id', 'exams_users_questions', ['question_id'], unique=False)
    op.create_index('ix_exam_user_question_user_exam_id', 'exams_users_questions', ['user_id', 'exam_id'], unique=False)
    op.create_index('ix_user_email_address', 'users', ['email_address'], unique=False)
    op.create_index('ix_user_external_id', 'users', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_external_id', table_name='users')
    op.drop_index('ix_user_email_address', table_name='users')
    op.drop_index('ix_exam_user_question_user_exam_id', table_name='exams_users_questions')
    op.drop_index('ix_exam_user_question_question_id', table_name='exams_users_questions')
    op.drop_index('ix_exam_user_question_group_organization_id', table_name='exams_users_questions')
    op.drop_index('ix_exam_user_exam_user_id', table_name='exams_users')
    op.drop_index('ix_exam_start_end_date', table_name='exams')
    op.drop_index('ix_exam_grade', table_name='exams')
    # ### end Alembic commands ###
