"""drop county columns

Revision ID: 80dc3596cd72
Revises: 15f6a3cd8319
Create Date: 2026-04-30 00:23:57.781444+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80dc3596cd72'
down_revision = '15f6a3cd8319'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'county')
    op.drop_column('users', 'county')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('county', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('county', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
