"""Add city_id to organizations and users

Revision ID: 4c20e02c3d1e
Revises: 1d38d854ea1f
Create Date: 2026-04-28 20:20:40.426897+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c20e02c3d1e'
down_revision = '1d38d854ea1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('city_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('city_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'city_id')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'city_id')
    # ### end Alembic commands ###
