"""Add on delete cascade to many-to-many tables

Revision ID: 181afb8d0e87
Revises: 16af67d788a2
Create Date: 2023-06-14 15:58:49.749899+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181afb8d0e87'
down_revision = '16af67d788a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exams_users_user_id_fkey', 'exams_users', type_='foreignkey')
    op.drop_constraint('exams_users_exam_id_fkey', 'exams_users', type_='foreignkey')
    op.create_foreign_key(None, 'exams_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exams_users', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('exams_users_questions_user_id_fkey', 'exams_users_questions', type_='foreignkey')
    op.drop_constraint('exams_users_questions_exam_id_fkey', 'exams_users_questions', type_='foreignkey')
    op.drop_constraint('exams_users_questions_question_id_fkey', 'exams_users_questions', type_='foreignkey')
    op.create_foreign_key(None, 'exams_users_questions', 'questions', ['question_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'exams_users_questions', 'exams', ['exam_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'exams_users_questions', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('users_groups_group_id_fkey', 'users_groups', type_='foreignkey')
    op.drop_constraint('users_groups_user_id_fkey', 'users_groups', type_='foreignkey')
    op.create_foreign_key(None, 'users_groups', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_groups', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_organizations_user_id_fkey', 'users_organizations', type_='foreignkey')
    op.drop_constraint('users_organizations_organization_id_fkey', 'users_organizations', type_='foreignkey')
    op.create_foreign_key(None, 'users_organizations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_organizations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_organizations', type_='foreignkey')
    op.drop_constraint(None, 'users_organizations', type_='foreignkey')
    op.create_foreign_key('users_organizations_organization_id_fkey', 'users_organizations', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('users_organizations_user_id_fkey', 'users_organizations', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'users_groups', type_='foreignkey')
    op.drop_constraint(None, 'users_groups', type_='foreignkey')
    op.create_foreign_key('users_groups_user_id_fkey', 'users_groups', 'users', ['user_id'], ['id'])
    op.create_foreign_key('users_groups_group_id_fkey', 'users_groups', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'exams_users_questions', type_='foreignkey')
    op.drop_constraint(None, 'exams_users_questions', type_='foreignkey')
    op.drop_constraint(None, 'exams_users_questions', type_='foreignkey')
    op.create_foreign_key('exams_users_questions_question_id_fkey', 'exams_users_questions', 'questions', ['question_id'], ['id'])
    op.create_foreign_key('exams_users_questions_exam_id_fkey', 'exams_users_questions', 'exams', ['exam_id'], ['id'])
    op.create_foreign_key('exams_users_questions_user_id_fkey', 'exams_users_questions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'exams_users', type_='foreignkey')
    op.drop_constraint(None, 'exams_users', type_='foreignkey')
    op.create_foreign_key('exams_users_exam_id_fkey', 'exams_users', 'exams', ['exam_id'], ['id'])
    op.create_foreign_key('exams_users_user_id_fkey', 'exams_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
